### PR TITLE
Added Twitter and become a member button (fix #20)

### LINKED ISSUE #20: add a few things to the community page
- @compsoc and @hacktheburgh on twitter
- the "become a member" big red button

### PR DESCRIPTION
**Pull request by rphi**
Added an embedded twitter timeline for CompSoc, and links to both CompSoc and Hacktheburgh as well as a button to join. Not entirely convinced by the layout myself but can't think of what else to do. Eh. never mind. (fix #20)

screen shot 2017-07-23 at 20 46 29

PS removed myself from main repo and am just going to work on a fork because that's probably safer.

### CODE REVIEW

**Comment by bnelo12** [comment]
I've checked out your branch and left some comments. Looks good!

**Comment by qaisjp** [comment]
This looks good.

Something to think about and discuss: what if we removed the FB page / tweet feed? This would mean the new "follow us on Twitter + become a member" column takes the place of the FB feed. The small FB page widget could be above the Discord button.

Thoughts? I know getting the feed to behave nicely was a bit of work, so I'm reluctant to change this with without discussion.

**Comment by bnelo12** [comment]
I would say try it out, and if it looks good, that's what we should go with.

**Comment by rphi** [comment]
I'd be tempted to move the Facebook feed into the place of the twitter feed, and also the facebook group links to the position of the Twitter page links (as the Facebook embed is a little more visually interesting than the Twitter). The advantage of the widgets is that they are a very easy way to make the site look more alive? (far easier to post to FB than the website)

Looking at it again, there is probably a little too much screen area dedicated to Twitter. Saying that, having a lot of things does make it feel that the community is larger...

One final thing, ditching any embeddables and just making our own buttons/links is far nicer from a load times perspective, and also reduces the bandwidth and tracking scripts running on the site which I'm sure a lot of people would appreciate. 

One final thing, could we add TARDIS to the links, granted not specifically CompSoc, but considering we share an IRC and it is quite closely related at the very least in terms of subject matter. (a tall two-color TARDIS button could potentially look very neat, and it could just link to tardis.pub because lol)

**Comment by qaisjp** [comment]
- ditching embeddables may be a good idea
- adding Tardis to the links is a good idea
- i feel the community page should not be a live feed but a page to see where compsoc has a presence

**Comment by rphi** [comment]
I shall start another branch on my fork and give it a try. (which could be fun considering I've pushed the footer changes to my master d'oh)

https://github.com/thepracticaldev/orly-full-res/blob/master/memorizingsixgitcommands-big.png

**Pull request merged**
