### PR TITLE
Added pagination to blog page

### PR DESCRIPTION
**Pull request by bnelo12**

### CODE REVIEW

**Comment by bnelo12** [comment]
screen shot 2017-07-26 at 9 35 53 am

**Comment by bnelo12** [comment]
This was pretty hard to implement. Jekyll doesn't support pagination when the page you are trying to paginate is inside a collection, so I had to pull the blog page out of the collection to the root directory as blog/index.html. It was super picky about paths. See here https://jekyllrb.com/docs/pagination/

**Comment by bnelo12** [comment]
I've left the test blogs I wrote in so you can see how it all works together, but I also noticed that the next and before buttons don't work within a blog post so some investigation will have to go into that.

**Comment by rphi** [comment]
This looks like "a basic jekyll install" is no longer going to work? Potentially the Readme might need updating.

**Comment by qaisjp** [comment]
it will need updating, yes

**Pull request merged**
